package br.com.digitalhouse.marmeladamovie.domain.utils

const val TOKEN = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZWYxNWJhYjY5YmNkNzQyNDMxM2ZhYWNkMmI4NDgwZSIsInN1YiI6IjVmZDNmMDEzYTBiNmI1MDAzZWZhZjQ4MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Tpuf2lzDd_z6PiM_iLafE1eWvz71lYWYb0W2jmVZALU"
